# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Basic Airflow cluster configuration for CeleryExecutor with Redis and PostgreSQL.
#
# WARNING: This configuration is for local development. Do not use it in a production deployment.
#
# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# AIRFLOW_IMAGE_NAME           - Docker image name used to run Airflow.
#                                Default: apache/airflow:2.5.1
# AIRFLOW_UID                  - User ID in Airflow containers
#                                Default: 50000
# AIRFLOW_PROJ_DIR             - Base path to which all the files will be volumed.
#                                Default: .
# Those configurations are useful mostly in case of standalone testing/running Airflow in test/try-out mode
#
# _AIRFLOW_WWW_USER_USERNAME   - Username for the administrator account (if requested).
#                                Default: airflow
# _AIRFLOW_WWW_USER_PASSWORD   - Password for the administrator account (if requested).
#                                Default: airflow
# _PIP_ADDITIONAL_REQUIREMENTS - Additional PIP requirements to add when starting all containers.
#                                Default: ''
#
# Feel free to modify this file to suit your needs.
---
version: '3.8'
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.1}
  build: 
    dockerfile: docker/airflow/Dockerfile
    args:
      DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_FOLDER: '/opt/airflow/dags/git-sync-dags'
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    AIRFLOW_VAR_DOCKER_URL: /var/run/docker.sock
  volumes:
    - git-sync-dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ./src/airflow/webserver_config.py:/opt/airflow/webserver_config.py
    - /var/run/docker.sock:/var/run/docker.sock
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - traefiknet
  group_add:
    - docker
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
    keycloak:
      condition: service_healthy
  env_file:
    - .env.idoml

networks:
  traefiknet:
    name: traefiknet

services:
  traefik:
    image: "traefik:v2.11"
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefiknet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./src/traefik/config:/etc/traefik/:ro

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - "8180:8080"
    env_file:
      - .env.idoml
    volumes:
      - ./src/keycloak:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/
    command:
      - start-dev --import-realm
    environment:
      KC_HEALTH_ENABLED: true
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idoml-keycloak.entrypoints=web"
      - "traefik.http.routers.idoml-keycloak.rule=Host(`keycloak.${IDOML_DOMAIN}`)"
  
  homarr:
    image: ghcr.io/serval-uni-lu/idoml-homarr:test
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./src/homarr/configs:/app/data/configs
      - ./src/homarr/icons:/app/public/icons
      - homarr-data:/data
    ports:
      - '7575:7575'
    environment:
      NEXTAUTH_URL: http://dashboard.${IDOML_DOMAIN}
      AUTH_PROVIDER: "oidc"
      AUTH_OIDC_URI: "http://keycloak.${IDOML_DOMAIN}/realms/idoml"
      AUTH_OIDC_CLIENT_SECRET: "client-secret-homarr"
      AUTH_OIDC_CLIENT_ID: "homarr"
      AUTH_OIDC_CLIENT_NAME: "IDOML"
      AUTH_OIDC_ADMIN_GROUP: "admin"
      AUTH_OIDC_OWNER_GROUP: "admin"
      IDOML_DOMAIN: ${IDOML_DOMAIN}
      AUTH_LOGOUT_REDIRECT_URL: "http://keycloak.${IDOML_DOMAIN}/realms/idoml/protocol/openid-connect/logout?client_id=homarr&post_logout_redirect_uri=http://dashboard.${IDOML_DOMAIN}"
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idoml-homarr.entrypoints=web"
      - "traefik.http.routers.idoml-homarr.rule=Host(`dashboard.${IDOML_DOMAIN}`)"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.idoml 
    networks:
      - traefiknet

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    networks:
      - traefiknet

  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v3.6.3
    user: root
    environment:
      GIT_SYNC_REPO: ${IDOML_GIT_DAG_REPO}
      GIT_SYNC_BRANCH: ${IDOML_GIT_DAG_BRANCH}
      GIT_SYNC_DEST: "git-sync-dags"
      GIT_SYNC_ROOT: "/opt/airflow/dags"
      GIT_SYNC_PERIOD: "10"
      # GIT_SYNC_SSH: true
      # GIT_SSH_KEY_FILE: "/etc/git-secret/idoml_deploy_key"
    restart: always
    volumes:
      - git-sync-dags:/opt/airflow/dags
      - ./secrets/ssh/:/etc/git-secret 
    labels:
      - "traefik.enable=false"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8280:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idoml-airflow-web.entrypoints=web"
      - "traefik.http.routers.idoml-airflow-web.rule=Host(`airflow.${IDOML_DOMAIN}`)"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      <<: *airflow-common-env
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        function ver() {
          printf "%04d%04d%04d%04d" $${1//./ }
        }
        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
        airflow_version_comparable=$$(ver $${airflow_version})
        min_airflow_version=2.2.0
        min_airflow_version_comparable=$$(ver $${min_airflow_version})
        if (( airflow_version_comparable < min_airflow_version_comparable )); then
          echo
          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
          echo
          exit 1
        fi
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow

  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
  # or by explicitly targeted on the command line e.g. docker-compose up flower.
  # See: https://docs.docker.com/compose/profiles/
  flower:
    <<: *airflow-common
    command: celery flower
    ports:
      - 5555:5555
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      # Console
      - "traefik.http.routers.router_flower.rule=Host(`flower.${IDOML_DOMAIN}`)"
      - "traefik.http.routers.router_flower.entrypoints=web"
      - "traefik.http.routers.router_flower.service=service_flower"
      - "traefik.http.services.service_flower.loadbalancer.server.port=5555"

  minio:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.idoml
    volumes:
      - storage-minio:/minio-data
    command: server --console-address ":9001" /minio-data
    restart: always # necessary since it's failing to start sometimes
    environment:
      MINIO_IDENTITY_OPENID_CLIENT_ID: minio
      MINIO_IDENTITY_OPENID_SCOPES: minio
      MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC: "on"
      MINIO_DOMAIN: minio.${IDOML_DOMAIN}
      # MINIO_SERVER_URL not working
      # MINIO_SERVER_URL: http://minio.${IDOML_DOMAIN}
      MINIO_BROWSER_REDIRECT_URL: http://console.minio.${IDOML_DOMAIN}
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      # Console
      - "traefik.http.routers.minio-console.rule=Host(`console.minio.${IDOML_DOMAIN}`)"
      - "traefik.http.routers.minio-console.entrypoints=web"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      # APi
      - "traefik.http.routers.minio.rule=Host(`minio.${IDOML_DOMAIN}`)"
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

  mc:
    image: quay.io/minio/mc:RELEASE.2024-02-24T01-33-20Z
    env_file:
      - .env.idoml
    networks:
      - traefiknet
    depends_on:
      minio: 
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set idoml-minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} &&
      /usr/bin/mc mb idoml-minio/airflow-logs;
      /usr/bin/mc mb idoml-minio/mlflow-idoml;
      /usr/bin/mc mb idoml-minio/datasets;
      exit 0;
      "
    labels:
      - "traefik.enable=false"

  mlflow:
    build: 
      dockerfile: docker/mlflow/Dockerfile
    command:
      - "mlflow"
      - "server"
      - "--backend-store-uri=postgresql://${DB_USER:-mlflow}:${DB_PASSWORD:-mlflow}@${DB_SERVER:-mlflow-db}:${DB_PORT:-5432}/${DB_NAME:-mlflow}"
      - "--default-artifact-root=s3://mlflow-idoml"
      - "-h 0.0.0.0"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      # - BACKEND=postgresql://${DB_USER:-mlflow}:${DB_PASSWORD:-mlflow}@${DB_SERVER:-db}:${DB_PORT:-5432}/${DB_NAME:-mlflow}
      - AWS_ACCESS_KEY_ID=${IDOML_MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${IDOML_MINIO_ROOT_PASSWORD}
    ports:
      - 5000
    networks:
      - traefiknet
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mlflow-idoml-endpoint.entrypoints=web"
      - "traefik.http.routers.mlflow-idoml-endpoint.rule=Host(`idoml.mlflow.${IDOML_DOMAIN}`)"
      - "traefik.http.routers.mlflow-idoml.entrypoints=web"
    restart: always
    depends_on:
      - mc
      - mlflow-db

  mlflow-db:
    restart: always
    image: postgres:13
    # container_name: idoml-mlflow-db-${USER_NAME}
    expose:
      - ${DB_PORT:-5432}
    environment:
      - POSTGRES_DB=${DB_NAME:-mlflow}
      - POSTGRES_USER=${DB_USER:-mlflow}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mlflow}
    volumes:
      - mlflow-db-volume:/var/lib/postgresql/data

volumes:
  postgres-db-volume:
  mlflow-db-volume:
  storage-minio:
  git-sync-dags:
  keycloak_data:
  homarr-data:
